## Gender Classification Of Names
### Using Machine Learning To Detect/Predict Gender of Individuals From their Names
+ Sklearn
+ Pandas
+ Text Extraction

In [95]:
# EDA packages
import pandas as pd
import numpy as np


In [96]:
# ML Packages
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer
#from sklearn.feature_extraction.text import TfidfVectorizer


In [97]:
# Load our data
df = pd.read_csv('gender.csv')

In [98]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [99]:
df.size

285075

In [100]:
# Data Cleaning
# Checking for column name consistency
df.columns

Index(['index', 'name', 'sex'], dtype='object')

In [101]:
# Data Types
df.dtypes

index     int64
name     object
sex      object
dtype: object

In [102]:
# Checking for Missing Values
df.isnull().isnull().sum()

index    0
name     0
sex      0
dtype: int64

In [103]:
# Number of Female Names
df[df.sex == 'F'].size

181800

In [104]:
# Number of Male Names
df[df.sex == 'M'].size

103275

In [105]:
df_names = df

In [106]:
# Replacing All F and M with 0 and 1 respectively
# df_names.sex.replace({'F': 0, 'M': 1}, inplace=True)
df_names['sex'] = df_names['sex'].replace({'F': 0, 'M': 1})

C:\Users\tanvo\AppData\Local\Temp\ipykernel_42356\3868284132.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_names['sex'] = df_names['sex'].replace({'F': 0, 'M': 1})


In [107]:
df_names.sex.unique()

array([0, 1], dtype=int64)

In [108]:
df_names.dtypes

index     int64
name     object
sex       int64
dtype: object

In [109]:
Xfeatures =df_names['name']

In [110]:
# Feature Extraction 
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures)

In [111]:
cv.get_feature_names_out()

array(['aaban', 'aabha', 'aabid', ..., 'zyyanna', 'zyyon', 'zzyzx'],
      dtype=object)

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
# Features 
X
# Labels
y = df_names.sex

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [115]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)


0.6398163206734908

In [116]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 63.98163206734908 %


In [117]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_train,y_train)*100,"%")

Accuracy of Model 100.0 %


### Sample Prediction

In [118]:
# Sample1 Prediction
sample_name = ["Mary"]
vect = cv.transform(sample_name).toarray()

In [119]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [120]:
# Female is 0, Male is 1
clf.predict(vect)

array([0], dtype=int64)

In [121]:
# Sample2 Prediction
sample_name1 = ["Mark"]
vect1 = cv.transform(sample_name1).toarray()

In [122]:
clf.predict(vect1)

array([1], dtype=int64)

In [123]:
# Sample3 Prediction of Russian Names
sample_name2 = ["Natasha"]
vect2 = cv.transform(sample_name2).toarray()

In [124]:
clf.predict(vect2)

array([0], dtype=int64)

In [125]:
# Sample3 Prediction of Random Names
sample_name3 = ["Nefertiti","Nasha","Ama","Ayo","Xhavier","Ovetta","Tathiana","Xia","Joseph","Xianliang"]
vect3 = cv.transform(sample_name3).toarray()

In [126]:
clf.predict(vect3)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [127]:
# A function to do it
def genderpredictor(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [128]:
genderpredictor("Martha")

Female


- Features fxn
- apply the fxn
- vectorizer
- fit
- transform
- classifier
- fit
- predict


In [129]:
namelist = ["Yaa","Yaw","Femi","Masha"]
for i in namelist:
    print(genderpredictor(i))

Female
None
Male
None
Female
None
Female
None


### Using a custom function for feature analysis

In [130]:
# By Analogy most female names ends in 'A' or 'E' or has the sound of 'A'
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [131]:
# Vectorize the features function
features = np.vectorize(features)
print(features(["Anna", "Hannah", "Peter","John","Vladmir","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'h', 'first2-letters': 'ha', 'first3-letters': 'han', 'last-letter': 'h', 'last2-letters': 'ah', 'last3-letters': 'nah'}
 {'first-letter': 'p', 'first2-letters': 'pe', 'first3-letters': 'pet', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ter'}
 {'first-letter': 'j', 'first2-letters': 'jo', 'first3-letters': 'joh', 'last-letter': 'n', 'last2-letters': 'hn', 'last3-letters': 'ohn'}
 {'first-letter': 'v', 'first2-letters': 'vl', 'first3-letters': 'vla', 'last-letter': 'r', 'last2-letters': 'ir', 'last3-letters': 'mir'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [132]:
# Extract the features for the dataset
df_X = features(df_names['name'])

In [133]:
df_y = df_names['sex']

In [134]:
from sklearn.feature_extraction import DictVectorizer
 
corpus = features(["Mike", "Julia"])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)
 

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 11)	1.0


In [135]:
dv.get_feature_names_out()

array(['first-letter=j', 'first-letter=m', 'first2-letters=ju',
       'first2-letters=mi', 'first3-letters=jul', 'first3-letters=mik',
       'last-letter=a', 'last-letter=e', 'last2-letters=ia',
       'last2-letters=ke', 'last3-letters=ike', 'last3-letters=lia'],
      dtype=object)

In [136]:
# Train Test Split
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [137]:
dfX_train

array([{'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'ele', 'last-letter': 'a', 'last2-letters': 'ia', 'last3-letters': 'nia'},
       {'first-letter': 'a', 'first2-letters': 'ad', 'first3-letters': 'adi', 'last-letter': 'l', 'last2-letters': 'il', 'last3-letters': 'dil'},
       {'first-letter': 'k', 'first2-letters': 'ka', 'first3-letters': 'kad', 'last-letter': 'e', 'last2-letters': 'ze', 'last3-letters': 'nze'},
       ...,
       {'first-letter': 'j', 'first2-letters': 'ja', 'first3-letters': 'jaz', 'last-letter': 'y', 'last2-letters': 'ly', 'last3-letters': 'zly'},
       {'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'elv', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'ina'},
       {'first-letter': 'l', 'first2-letters': 'le', 'first3-letters': 'led', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ger'}],
      dtype=object)

In [138]:

dv = DictVectorizer()
dv.fit_transform(dfX_train)


<63666x8194 sparse matrix of type '<class 'numpy.float64'>'
	with 381996 stored elements in Compressed Sparse Row format>

In [139]:
# Model building Using DecisionTree

from sklearn.tree import DecisionTreeClassifier
 
dclf = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dclf.fit(my_xfeatures, dfy_train)


DecisionTreeClassifier()

In [140]:
# Build Features and Transform them
sample_name_eg = ["Alex"]
transform_dv =dv.transform(features(sample_name_eg))


In [141]:
vect3 = transform_dv.toarray()

In [142]:
# Predicting Gender of Name
# Male is 1,female = 0
dclf.predict(vect3)

array([1], dtype=int64)

In [143]:
if dclf.predict(vect3) == 0:
    print("Female")
else:
    print("Male")

Male


In [144]:
# Second Prediction With Nigerian Name
name_eg1 = ["Chioma"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Female


In [145]:
# A function to do it
def genderpredictor1(a):
    test_name1 = [a]
    transform_dv =dv.transform(features(test_name1))
    vector = transform_dv.toarray()
    if dclf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [146]:
random_name_list = ["Alex","Alice","Chioma","Vitalic","Clairese","Chan"]

In [147]:
for n in random_name_list:
    print(genderpredictor1(n))

Male
None
Female
None
Female
None
Female
None
Female
None
Male
None


In [148]:
## Accuracy of Models Decision Tree Classifier Works better than Naive Bayes
# Accuracy on training set
print(dclf.score(dv.transform(dfX_train), dfy_train)) 
 

0.9888951716771903


In [149]:
# Accuracy on test set
print(dclf.score(dv.transform(dfX_test), dfy_test))

0.8671194872285468


### Saving Our Model

In [150]:
import joblib

In [151]:
decisiontreModel = open("decisiontreemodel.pkl","wb")

In [152]:
joblib.dump(dclf,decisiontreModel)

In [153]:
decisiontreModel.close

<function BufferedWriter.close()>

In [154]:
#Alternative to Model Saving
import pickle
dctreeModel = open("namesdetectormodel.pkl","wb")

In [155]:
pickle.dump(dclf,dctreeModel)

In [156]:
dctreeModel.close()

##### Save Multinomial NB Model

In [157]:
NaiveBayesModel = open("../models/naivebayesgendermodel.pkl","wb")

In [158]:
joblib.dump(clf,NaiveBayesModel)

In [159]:
NaiveBayesModel.close()

In [160]:
# Thanks To
# Jesse JCharis
# Jesus Saves @ JCharisTech
# J-Secur1ty